### ISSUE TITLE
Which phone number, which account

### ISSUE THREAD

**Issue by elahimanesh** [ahmdrz/instagram-contacts#1]
Hi Ahmadreza
Thank you for this repository.
How is it possible to figure out which phone number is associated with each account?

**Comment by piorphism** [comment]
same issue

**Comment by ahmdrz** [comment]
Hi,
Some months ago, we've could assign users to their phone numbers based on their indices.
But now there is no way to figure out.

**Comment by piorphism** [comment]
Is not it possible to assign telephone numbers as 'addressbook_name' variable and get it result['items']?
